### ISSUE TITLE
可否支持less编译后再压缩合并css？

### ISSUE THREAD

**Issue by hehaibao** [dnxbf321/gulp-htmloptimize#1]
大神，请教下，按照您这种方式，如何实现先编译less文件，然后成功后再压缩合并 生成后的css文件呢？

**Comment by dnxbf321** [comment]
此项目已非常陈旧。这里的打包方式并不是很好，如果你有兴趣，不放尝试我目前正维护的另一个项目 [node-project-template](https://github.com/dnxbf321/node-project-template)。
